# Generated by Django 5.0.6 on 2024-06-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='isbn',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='price',
            field=models.IntegerField(),
        ),
    ]
